### ISSUE TITLE
Problem installing with Garden

### ISSUE THREAD

**Issue by ThatCyanPlayer** [kivy-garden/kivy-garden.github.io#122] opened 2016-10-23 00:18 UTC
I am having an issue running Garden,

I am trying to install https://github.com/kivy-garden/garden.cefpython

I run: garden install cefpython

Output:
Downloading http://github.com/kivy-garden/garden.cefpython/archive/master.zip ...
('Progression', 2939904, '-', '\r')
('Progression', 2940928, '\', '\r')
('Progression', 2941952, '|', '\r')
('Progression', 2942976, '/', '\r')
('Progression', 2944000, '-', '\r')
('Progression', 2945024, '\', '\r')
('Progression', 2946048, '|', '\r')
('Progression', 2947072, '/', '\r')
('Progression', 2948096, '-', '\r')
('Progression', 2949120, '\', '\r')
('Progression', 2950144, '|', '\r')
('Progression', 2951168, '/', '\r')
('Progression', 2952192, '-', '\r')
('Progression', 2953216, '\', '\r')
('Progression', 2954240, '|', '\r')
('Progression', 2955264, '/', '\r')
('Progression', 2956288, '-', '\r')
('Progression', 2957312, '\', '\r')
('Progression', 2958336, '|', '\r')
('Progression', 2959360, '/', '\r')
('Progression', 2960384, '-', '\r')
('Progression', 2961408, '\', '\r')
('Progression', 2962432, '|', '\r')
('Progression', 2963456, '/', '\r')
('Progression', 2964480, '-', '\r')
('Progression', 2965504, '\', '\r')
('Progression', 2966528, '|', '\r')
('Progression', 2967552, '/', '\r')
('Progression', 2968576, '-', '\r')
('Progression', 2969600, '\', '\r')
('Progression', 2970624, '|', '\r')
('Progression', 2971648, '/', '\r')
('Progression', 2972672, '-', '\r')
('Progression', 2973696, '\', '\r')
('Progression', 2974720, '|', '\r')
('Progression', 2975744, '/', '\r')
('Progression', 2976768, '-', '\r')
('Progression', 2977792, '\', '\r')
('Progression', 2978816, '|', '\r')
('Progression', 2979840, '/', '\r')
('Progression', 2980864, '-', '\r')
('Progression', 2981888, '\', '\r')
('Progression', 2982912, '|', '\r')
('Progression', 2983936, '/', '\r')
('Progression', 2984960, '-', '\r')
('Progression', 2985984, '\', '\r')
('Progression', 2987008, '|', '\r')
('Progression', 2988032, '/', '\r')
('Progression', 2989056, '-', '\r')
('Progression', 2990080, '\', '\r')
('Progression', 2991104, '|', '\r')
('Progression', 2992128, '/', '\r')
('Progression', 2993152, '-', '\r')
('Progression', 2994176, '\', '\r')
('Progression', 2995200, '|', '\r')
('Progression', 2996224, '/', '\r')
('Progression', 2997248, '-', '\r')
('Progression', 2998272, '\', '\r')
('Progression', 2999296, '|', '\r')
('Progression', 3000320, '/', '\r')
('Progression', 3001344, '-', '\r')
('Progression', 3002368, '\', '\r')
('Progression', 3003392, '|', '\r')
('Progression', 3004416, '/', '\r')
('Progression', 3005440, '-', '\r')
....... endlessly.

**Comment by dessant** [comment] 2016-11-04 22:51
Duplicate of https://github.com/kivy-garden/garden/issues/7.

You could download and place the repo in `~/.kivy/garden` as a workaround, try installing a different flower to see how is the folder populated.

**Closed by dessant** 2016-11-04 22:51 UTC
